name: Build Resource Pack

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create ZIP
        run: zip -r generated.zip . -x "*/.github/*" -x "*/.git/*" -x "README*"

      - name: Delete old release
        run: gh release delete latest --yes || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Resource Pack
          files: generated.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
